version: '3'
services:
  openldap:
    image: osixia/openldap:1.5.0
    restart: always
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "ValueLabs"
      LDAP_DOMAIN: "valuelabs.com"
      LDAP_ADMIN_PASSWORD: "Rat3onal"
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
