---
micronaut:
  application:
    name: registrationService
  metrics:
    enabled: true
    export:
      datadog:
        enabled: false
        step: PT1M
        descriptions: true
        apiKey: "dummy-key-for-development"
  environments:
    development:
      metrics:
        enabled: false
        export:
          datadog:
            enabled: false
            step: PT1M
            descriptions: true
            apiKey: "dummy-key-for-development"
      micronaut:
        metrics:
          enabled: false
          export:
            datadog:
              enabled: false
              apiKey: null
    production:
      config:
        registration: {}
  executors:
    scheduled:
      type: scheduled
      corePoolSize: 16
  rateLimits:
    checkVerificationCode:
      delays: 60s
    leakyBucket:
      sessionCreation:
        name: registration
        maxCapacity: 100
        permitRegenerationPeriod: 10s
        minDelay: 25s
    sendSmsVerificationCode:
      delays: 10s
    sendVoiceVerificationCode:
      delayAfterFirstSms: 120s
      delays: 60s
  config:
    registration:
      directory:
        type: ENTRA_ID

        # LDAP Configuration
        ldap:
          url: ldap://localhost:389
          baseDn: dc=valuelabsdc=com
          useSsl: false
          trustStore: ${TRUST_STORE}
          trustStorePassword: ${TRUST_STORE_PASSWORD}
          trustStoreType: JKS
          hostnameVerification: true
          connectionTimeout: 30000
          readTimeout: 30000
          minPoolSize: 3
          maxPoolSize: 10
          poolTimeout: 300000
          maxRetries: 3
          userFilter: (userPrincipalName={0})
          bindDn: cn=admin,cn=users,dc=valuelabs,dc=com
          bindPassword: ${LDAP_BIND_PASSWORD}
          phoneNumberAttribute: mobile

        # Entra ID Configuration
        entra-id:
          tenant-id: ${ENTRA_TENANT_ID}
          client-id: ${ENTRA_CLIENT_ID}
          client-secret: ${ENTRA_CLIENT_SECRET}
          test-user: ${ENTRA_TEST_USER}
          test-password: ${ENTRA_TEST_PASSWORD}
          phone-number-attribute: mobilePhone  # Can be mobilePhone, otherMobile, businessPhones, etc.

messagebird:
   enabled: false

bigtable:
  enabled: false

gcp:
  enabled: false

twilio:
  enabled: false

infobip:
  enabled: false

selection:
  sms:
    transport: NONE
    fallbackSenders: ["last-digits-of-phone-number"]
  voice:
    transport: VOICE
    fallbackSenders: ["last-digits-of-phone-number"]
    defaultWeights:
      last-digits-of-phone-number: 100
    regionWeights: {}
    regionOverrides: {}

grpc:
  server:
    endpoint: localhost
    port: 50051
