---
micronaut:
  application:
    name: registrationService
  environments:
    development:
      environments: true
  server:
    host: 0.0.0.0
    port: 8080
    httpVersion: 1.1
  metrics:
    binders:
      netty:
        queues:
          enabled: false
    export:
      datadog:
        enabled: false
        step: 20s
    tags:
      service: registration
  executors:
    scheduled:
      type: scheduled
      corePoolSize: 16
  rateLimits:
    checkVerificationCode:
      delays: 60s
    leakyBucket:
      sessionCreation:
        name: registration
        maxCapacity: 100
        permitRegenerationPeriod: 10s
        minDelay: 25s
    sendSmsVerificationCode:
      delays: 10s
    sendVoiceVerificationCode:
      delayAfterFirstSms: 120s
      delays: 60s
  config:
    registration:
      useLdap: true
      ldap:
        # LDAP server connection settings
        url: ldap://localhost:389
        baseDn: dc=valuelabs,dc=com
        useSsl: false
        minPoolSize: 3
        maxPoolSize: 10
        timeout: 300000
        userFilter: (uid={0})
        bindDn: cn=admin,dc=valuelabs,dc=com
        bindPassword: Rat3onal
        phoneNumberAttribute: mobile
        testPhoneNumber: +12025550123

selection:
  sms:
    transport: SMS
    fallbackSenders: ["last-digits-of-phone-number"]
    defaultWeights:
      last-digits-of-phone-number: 100
  voice:
    transport: VOICE
    fallbackSenders: ["last-digits-of-phone-number"]
    defaultWeights:
      last-digits-of-phone-number: 100

grpc:
  server:
    endpoint: localhost
    port: 50051
