---
micronaut:
  application:
    name: registrationService
  metrics:
    enabled: true
    export:
      datadog:
        enabled: false
  environments:
    development:
      micronaut:
        metrics:
          export:
            datadog:
              enabled: false
      environments: true
      config:
        registration:
          useLdap: true
    production:
      config:
        registration:
          useLdap: true
  executors:
    scheduled:
      type: scheduled
      corePoolSize: 16
  rateLimits:
    checkVerificationCode:
      delays: 60s
    leakyBucket:
      sessionCreation:
        name: registration
        maxCapacity: 100
        permitRegenerationPeriod: 10s
        minDelay: 25s
    sendSmsVerificationCode:
      delays: 10s
    sendVoiceVerificationCode:
      delayAfterFirstSms: 120s
      delays: 60s
  config:
    registration:
      ldap:
        # LDAP server connection settings
        url: ldap://localhost:389
        baseDn: dc=valuelabs,dc=com
        useSsl: false
        trustStore: /Users/jgnoonan/registration-service/src/main/resources/certs/truststore.jks
        trustStorePassword: changeit
        trustStoreType: JKS
        hostnameVerification: true
        connectionTimeout: 30000
        readTimeout: 30000
        minPoolSize: 3
        maxPoolSize: 10
        poolTimeout: 300000
        maxRetries: 3
        userFilter: (uid={0})
        bindDn: cn=admin,dc=valuelabs,dc=com
        bindPassword: Rat3onal
        phoneNumberAttribute: mobile

messagebird:
  enabled: false

bigtable:
  enabled: false

gcp:
  enabled: false

twilio:
  enabled: false

infobip:
  enabled: false

selection:
  sms:
    transport: NONE
    fallbackSenders: ["last-digits-of-phone-number"]
  voice:
    transport: VOICE
    fallbackSenders: ["last-digits-of-phone-number"]
    defaultWeights:
      last-digits-of-phone-number: 100

grpc:
  server:
    endpoint: localhost
    port: 50051
