---
micronaut:
  application:
    name: registrationService
  server:
    host: 0.0.0.0
    port: 8080
    http-version: 1.1
  metrics:
    binders:
      netty:
        queues:
          enabled: true
    export:
      datadog:
        enabled: false
        step: 20s
    tags:
      service: registration
  executors:
    scheduled:
      type: scheduled
      core-pool-size: 16
  registration:
    useldap: true
    ldap:
      url: ldap://localhost:389
      baseDn: dc=valuelabs,dc=com
      userFilter: (uid={0})
      bindDn: cn=admin,dc=valuelabs,dc=com
      bindPassword: Rat3onal
  logging:
    level:
      ROOT: TRACE
      io.micronaut.context.env: TRACE
      io.netty: DEBUG
      io.micronaut.http: DEBUG
grpc:
  server:
    port: 50051 # gRPC server for HTTP/2
