---
micronaut:
  application:
    name: registrationService
  metrics:
    enabled: true
    export:
      datadog:
        enabled: false
  environments:
    development:
      micronaut:
        metrics:
          export:
            datadog:
              enabled: false
      environments: true
      config:
        registration:
          useLdap: false
    production:
      config:
        registration:
          useLdap: false
  executors:
    scheduled:
      type: scheduled
      corePoolSize: 16
  rateLimits:
    checkVerificationCode:
      delays: 60s
    leakyBucket:
      sessionCreation:
        name: registration
        maxCapacity: 100
        permitRegenerationPeriod: 10s
        minDelay: 25s
    sendSmsVerificationCode:
      delays: 10s
    sendVoiceVerificationCode:
      delayAfterFirstSms: 120s
      delays: 60s
  config:
    registration:
      # Directory service type configuration
      directory:
        type: ENTRA_ID

      # LDAP Configuration
      ldap:
        enabled: false
        url: ldaps://2f8b8c95-8509-4822-a393-dc8f12d2c829.onmicrosoft.com:636
        baseDn: DC=comcast,DC=net
        useSsl: true
        trustStore: /Users/jgnoonan/registration-service/src/main/resources/certs/truststore.jks
        trustStorePassword: changeit
        trustStoreType: JKS
        hostnameVerification: true
        connectionTimeout: 30000
        readTimeout: 30000
        minPoolSize: 3
        maxPoolSize: 10
        poolTimeout: 300000
        maxRetries: 3
        userFilter: (userPrincipalName={0})
        bindDn: ${ENTRA_CLIENT_ID}@comcast.net
        bindPassword: ${ENTRA_CLIENT_SECRET}
        phoneNumberAttribute: mobile

      entra-id:
        enabled: true
        tenant-id: "2f8b8c95-8509-4822-a393-dc8f12d2c829"
        client-id: "bcd5ed86-07a1-4528-9c44-32e86b3e79ee"
        client-secret: ${ENTRA_CLIENT_SECRET}
        test-user: "jgnoonan_comcast.net#EXT#@jgnoonancomcast.onmicrosoft.com"
        test-password: "6MaDVWPMR9pAkWreWkvN7LtRD"

        # certificate-path: "${ENTRA_CERTIFICATE_PATH}"  # Alternative to client secret

messagebird:
   enabled: false

bigtable:
  enabled: false

gcp:
  enabled: false

twilio:
  enabled: false

infobip:
  enabled: false

selection:
  sms:
    transport: NONE
    fallbackSenders: ["last-digits-of-phone-number"]
  voice:
    transport: VOICE
    fallbackSenders: ["last-digits-of-phone-number"]
    defaultWeights:
      last-digits-of-phone-number: 100
    regionWeights: {}
    regionOverrides: {}

grpc:
  server:
    endpoint: localhost
    port: 50051
