---
micronaut:
  application:
    name: registrationService
  server:
    host: 0.0.0.0
    port: 8080
    http-version: 1.1
  metrics:
    binders:
      netty:
        queues:
          enabled: false
    export:
      datadog:
        enabled: false
        step: 20s
    tags:
      service: registration
  executors:
    scheduled:
      type: scheduled
      core-pool-size: 16
  rate-limits:
    check-verification-code:
      delays: 60s
    leaky-bucket:
      session-creation:
        name: registration
        max-capacity: 100
        permit-regeneration-period: 10s
        min-delay: 25s
    send-sms-verification-code:
      delays: 10s
    send-voice-verification-code:
      delay-after-first-sms: 120s
      delays: 60s
  registration:
    useldap: true
    ldap:
      url: ldap://localhost:389
      baseDn: dc=valuelabs,dc=com
      userFilter: (uid={0})
      bindDn: cn=admin,dc=valuelabs,dc=com
      bindPassword: Rat3onal
grpc:
  server:
    endpoint: localhost
    port: 50051
